[package]
name = "lighthouse"
version = "0.1.0"
authors = ["root"]

[[bin]]
name = "server"
path = "src/server/bin/main.rs"

[[bin]]
name = "client"
path = "src/client/bin/main.rs"

[dependencies]
sodiumoxide = "0.2.0"